apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Kustomization이 관리할 리소스 목록을 정의
resources:
- hello-app-deployment.yaml
images:
- name: myanjini/hello-app
  newName: myanjini/hello-app
  newTag: bdc66ed
